### ISSUE TITLE
fail to get genesis block

### ISSUE THREAD

**Issue by smallthing-hub** [hyperledger/fabric-sdk-py#121]
My fabric-version is 2.0, python-version is 3.7.     How can I what to do? The fabric network is running.

Traceback (most recent call last):
  File "train.py", line 33, in <module>
    orderer='orderer.example.com'
  File "/usr/local/python3/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/usr/local/python3/lib/python3.7/site-packages/fabric_sdk_py-0.9.0-py3.7.egg/hfc/fabric/client.py", line 654, in channel_join
    raise Exception(msg)
Exception: fail to get genesis block

Please help me! Thanks a lot!

**Comment by dexhunter** [comment]
@smallthing-hub Hi, I think the version is a problem currently, we haven't fully support Fabric v2.x
