### ISSUE TITLE
enroll admin error

### ISSUE THREAD

**Issue by DSSLab-code** [hyperledger/fabric-sdk-py#134]
Hi, all!

I set all the environment locally and run the fabcar example in fabric_sample. 
downloaded this python version sdk, run : adminEnrollment = casvc.enroll("admin","adminpw") 

the error shows like: json.decoder.JSONDecodeError expecting value: line 1 column 1 (char 0)

I was blocked by this error for 2 days, if anyone knows why just let me know, many thanks!

Init client with profile=test/fixtures/network.json
create org with name=orderer.example.com
create org with name=org1.example.com
create org with name=org2.example.com
create ca with name=ca-org1
create ca with name=ca-org2
Import orderers = dict_keys(['orderer.example.com'])
Import peers = dict_keys(['peer0.org1.example.com', 'peer1.org1.example.com', 'peer0.org2.example.com', 'peer1.org2.example.com'])
Traceback (most recent call last):
  File "lr.py", line 61, in <module>
    adminEnrollment = casvc.enroll("admin","adminpw") # now local will have the admin enrollment
  File "/home/yusen/Desktop/fabric-sdk-py/hfc/fabric_ca/caservice.py", line 484, in enroll
    enrollmentCert, caCertChain = self._ca_client.enroll(
  File "/home/yusen/Desktop/fabric-sdk-py/hfc/fabric_ca/caservice.py", line 328, in enroll
    res, st = self._send_ca_post(path='enroll',
  File "/home/yusen/Desktop/fabric-sdk-py/hfc/fabric_ca/caservice.py", line 255, in _send_ca_post
    return r.json(), r.status_code
  File "/home/yusen/anaconda3/lib/python3.8/site-packages/requests/models.py", line 889, in json
    return complexjson.loads(
  File "/home/yusen/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/yusen/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/yusen/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
**json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)**

**Comment by DSSLab-code** [comment]
Well, if I use the internal example of up the fabric network, it works. 
E.g run this: docker-compose -f test/fixtures/docker-compose-2orgs-4peers-tls.yaml up

**Comment by dexhunter** [comment]
Which version of fabric & fabcar are you using?
