### ISSUE TITLE
Build failure due to cryptography 3.4.7

### ISSUE THREAD

**Issue by rranjan3** [hyperledger/fabric-sdk-py#154]
The farbic-py-sdk is unable to build on CentOS 8.0.
While processing dependencies for fabric-py-sdk==0.9.0, the build looks for cryptography>=1.9 and ends up on version 3.4.7. The corresponding setup.py throws a  error.

However at times it ends up on 2.1.4. Then the build goes through fine.
 
Logs below for the error scenario - 

[2021-06-30T14:04:42.635Z] Searching for cryptography>=1.9
[2021-06-30T14:04:42.635Z] Reading https://pypi.org/simple/cryptography/
[2021-06-30T14:04:44.060Z] Downloading https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz#sha256=3d10de8116d25649631977cb37da6cbdd2d6fa0e0281d014a5b7d337255ca713
[2021-06-30T14:04:44.331Z] Best match: cryptography 3.4.7
[2021-06-30T14:04:44.331Z] Processing cryptography-3.4.7.tar.gz
[2021-06-30T14:04:44.331Z] Writing /tmp/easy_install-tgr1m2va/cryptography-3.4.7/setup.cfg
[2021-06-30T14:04:44.331Z] Running cryptography-3.4.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-tgr1m2va/cryptography-3.4.7/egg-dist-tmp-7b5pxrsu
[2021-06-30T14:04:44.768Z] 
[2021-06-30T14:04:44.768Z]         =============================DEBUG ASSISTANCE==========================
[2021-06-30T14:04:44.768Z]         If you are seeing an error here please try the following to
[2021-06-30T14:04:44.768Z]         successfully install cryptography:
[2021-06-30T14:04:44.768Z] 
[2021-06-30T14:04:44.768Z]         Upgrade to the latest pip and try again. This will fix errors for most
[2021-06-30T14:04:44.768Z]         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
[2021-06-30T14:04:44.768Z]         =============================DEBUG ASSISTANCE==========================
[2021-06-30T14:04:44.768Z]         
[2021-06-30T14:04:44.768Z] [91mTraceback (most recent call last):
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
[2021-06-30T14:04:44.768Z]     yield saved
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
[2021-06-30T14:04:44.768Z]     yield
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
[2021-06-30T14:04:44.768Z]     _execfile(setup_script, ns)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
[2021-06-30T14:04:44.768Z]     exec(code, globals, locals)
[2021-06-30T14:04:44.768Z]   File "/tmp/easy_install-tgr1m2va/cryptography-3.4.7/setup.py", line 14, in <module>
[2021-06-30T14:04:44.768Z]     with open('./requirements.txt') as reqs_txt:
[2021-06-30T14:04:44.768Z] ModuleNotFoundError: No module named 'setuptools_rust'
[2021-06-30T14:04:44.768Z] 
[2021-06-30T14:04:44.768Z] During handling of the above exception, another exception occurred:
[2021-06-30T14:04:44.768Z] 
[2021-06-30T14:04:44.768Z] Traceback (most recent call last):
[2021-06-30T14:04:44.768Z]   File "setup.py", line 46, in <module>
[2021-06-30T14:04:44.768Z]     include_package_data=True,
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
[2021-06-30T14:04:44.768Z]     return distutils.core.setup(**attrs)
[2021-06-30T14:04:44.768Z]   File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
[2021-06-30T14:04:44.768Z]     dist.run_commands()
[2021-06-30T14:04:44.768Z]   File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
[2021-06-30T14:04:44.768Z]     self.run_command(cmd)
[2021-06-30T14:04:44.768Z]   File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
[2021-06-30T14:04:44.768Z]     cmd_obj.run()
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
[2021-06-30T14:04:44.768Z]     self.do_egg_install()
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 117, in do_egg_install
[2021-06-30T14:04:44.768Z]     cmd.run()
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 411, in run
[2021-06-30T14:04:44.768Z]     self.easy_install(spec, not self.no_deps)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
[2021-06-30T14:04:44.768Z]     return self.install_item(None, spec, tmpdir, deps, True)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 706, in install_item
[2021-06-30T14:04:44.768Z]     self.process_distribution(spec, dist, deps)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 751, in process_distribution
[2021-06-30T14:04:44.768Z]     [requirement], self.local_index, self.easy_install
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 770, in resolve
[2021-06-30T14:04:44.768Z]     replace_conflicting=replace_conflicting
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1053, in best_match
[2021-06-30T14:04:44.768Z]     return self.obtain(req, installer)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in obtain
[2021-06-30T14:04:44.768Z]     return installer(requirement)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 678, in easy_install
[2021-06-30T14:04:44.768Z]     return self.install_item(spec, dist.location, tmpdir, deps)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 704, in install_item
[2021-06-30T14:04:44.768Z]     dists = self.install_eggs(spec, download, tmpdir)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 889, in install_eggs
[2021-06-30T14:04:44.768Z]     return self.build_and_install(setup_script, setup_base)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1157, in build_and_install
[2021-06-30T14:04:44.768Z]     self.run_setup(setup_script, setup_base, args)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1143, in run_setup
[2021-06-30T14:04:44.768Z]     run_setup(setup_script, args)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
[2021-06-30T14:04:44.768Z]     raise
[2021-06-30T14:04:44.768Z]   File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
[2021-06-30T14:04:44.768Z]     self.gen.throw(type, value, traceback)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
[2021-06-30T14:04:44.768Z]     yield
[2021-06-30T14:04:44.768Z]   File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
[2021-06-30T14:04:44.768Z]     self.gen.throw(type, value, traceback)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
[2021-06-30T14:04:44.768Z]     saved_exc.resume()
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
[2021-06-30T14:04:44.768Z]     six.reraise(type, exc, self._tb)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
[2021-06-30T14:04:44.768Z]     raise value.with_traceback(tb)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
[2021-06-30T14:04:44.768Z]     yield saved
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
[2021-06-30T14:04:44.768Z]     yield
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
[2021-06-30T14:04:44.768Z]     _execfile(setup_script, ns)
[2021-06-30T14:04:44.768Z]   File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
[2021-06-30T14:04:44.768Z]     exec(code, globals, locals)
[2021-06-30T14:04:44.768Z]   File "/tmp/easy_install-tgr1m2va/cryptography-3.4.7/setup.py", line 14, in <module>
[2021-06-30T14:04:44.768Z]     with open('./requirements.txt') as reqs_txt:
[2021-06-30T14:04:44.768Z] ModuleNotFoundError: No module named 'setuptools_rust'
[2021-06-30T14:04:44.768Z] [0m[91mmake: *** [Makefile:85: install] Error 1

**Comment by yeasy** [comment]
Would suggest specify a lower version of cryptography.
We have not tested with CentOS 8.0 yet.
Anyone has such an OS to give it a try? Let me know, thanks!
