### ISSUE TITLE
Ask on chaincode install error

### ISSUE THREAD

**Issue by znss1989** [hyperledger/fabric-sdk-py#87]
Hi, I was trying to install some chaincode into a created channel, just as in the tutorial documentation.

```python
    response = await cli.chaincode_install(
        requestor=org1_admin,
        peers=['peer0.org1.example.com', 'peer1.org1.example.com'],
        cc_path='github.com/example_cc',
        cc_name='example_cc',
        cc_version='v1.0')
```

But got the following report back. 

```
  File "fabric-exp.py", line 71, in async_main
    response = await cli.chaincode_install(
  File "/home/wul4/sofie/projects/interledger/il-dev/lib/python3.8/site-packages/fabric_sdk_py-0.8.1-py3.8.egg/hfc/fabric/client.py", line 1188, in chaincode_install
    responses, proposal, header = self.send_install_proposal(tx_context,
  File "/home/wul4/sofie/projects/interledger/il-dev/lib/python3.8/site-packages/fabric_sdk_py-0.8.1-py3.8.egg/hfc/fabric/client.py", line 1074, in send_install_proposal
    return utils.send_install_proposal(tx_context, peers)
  File "/home/wul4/sofie/projects/interledger/il-dev/lib/python3.8/site-packages/fabric_sdk_py-0.8.1-py3.8.egg/hfc/util/utils.py", line 400, in send_install_proposal
    package_chaincode(
  File "/home/wul4/sofie/projects/interledger/il-dev/lib/python3.8/site-packages/fabric_sdk_py-0.8.1-py3.8.egg/hfc/util/utils.py", line 500, in package_chaincode
    dist.addfile(tarinfo, f)
  File "/home/wul4/sofie/projects/interledger/il-dev/lib/python3.8/tarfile.py", line 1989, in addfile
    buf = tarinfo.tobuf(self.format, self.encoding, self.errors)
  File "/home/wul4/sofie/projects/interledger/il-dev/lib/python3.8/tarfile.py", line 826, in tobuf
    return self.create_pax_header(info, encoding)
  File "/home/wul4/sofie/projects/interledger/il-dev/lib/python3.8/tarfile.py", line 900, in create_pax_header
    buf = self._create_pax_generic_header(pax_headers, XHDTYPE, encoding)
  File "/home/wul4/sofie/projects/interledger/il-dev/lib/python3.8/tarfile.py", line 994, in _create_pax_generic_header
    value.encode("utf-8", "strict")
AttributeError: 'int' object has no attribute 'encode'
Exception ignored in: <function _Stream.__del__ at 0x7f14cde99700>
Traceback (most recent call last):
  File "/home/wul4/sofie/projects/interledger/il-dev/lib/python3.8/tarfile.py", line 410, in __del__
  File "/home/wul4/sofie/projects/interledger/il-dev/lib/python3.8/tarfile.py", line 458, in close
ValueError: I/O operation on closed file.
```

Is there any further setup required? Or any other reasons that might cause such problems?

**Comment by dexhunter** [comment]
it's caused by tarfile format which has been fixed at [this commit](https://github.com/hyperledger/fabric-sdk-py/commit/74b7e87ba7394bf393601f8974cfa6ad37f334c3). Please update to latest version

**Comment by znss1989** [comment]
I am using v0.8.1 of the SDK, I suppose that is the latest, right? And is Python3.8 a problem for this error?

**Comment by dexhunter** [comment]
yep, there is some updates in python3.8 causing the problem. Can you just use the source code then? We will release a LTS version for supporting fabric 1.4.x soon

**Comment by znss1989** [comment]
OK, I will try to work around with source code, or use a different python version. Thanks for the help.
